// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sales.Api.Data;


#nullable disable

namespace Sales_API.Migrations
{
    [DbContext(typeof(SalesContext))]
    [Migration("20250905122409_SalesInit")]
    partial class SalesInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sales_API.Models.OrderAgg.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ShoppingCartId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingCartId")
                        .IsUnique();

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Sales_API.Models.PaymentTransactionAgg.PaymentTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PaymentTransactionId")
                        .HasColumnType("bigint");

                    b.Property<long>("TransactionAmount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("TransactionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentTransactionId");

                    b.ToTable("PaymentTransactions", (string)null);
                });

            modelBuilder.Entity("Sales_API.Models.ShoppingCartAgg.ShoppingCart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCarts", (string)null);
                });

            modelBuilder.Entity("Sales_API.Models.OrderAgg.Order", b =>
                {
                    b.HasOne("Sales_API.Models.ShoppingCartAgg.ShoppingCart", "ShoppingCart")
                        .WithOne()
                        .HasForeignKey("Sales_API.Models.OrderAgg.Order", "ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Sales_API.Models.OrderAgg.ReceiverInformationValueObject", "ReceiverInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.Property<string>("ContactNumber")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(25)
                                .HasColumnType("nvarchar(25)");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.HasKey("Id");

                            b1.ToTable("ReceiverInformation", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("ReceiverInfo");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("Sales_API.Models.PaymentTransactionAgg.PaymentTransaction", b =>
                {
                    b.HasOne("Sales_API.Models.OrderAgg.Order", "Order")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sales_API.Models.PaymentTransactionAgg.PaymentTransaction", null)
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("PaymentTransactionId");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Sales_API.Models.ShoppingCartAgg.ShoppingCart", b =>
                {
                    b.OwnsMany("ShoppingCartItemValueObject", "CartItems", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<long>("ProductItemId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.Property<long>("ShoppingCartId")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("ShoppingCartId");

                            b1.ToTable("ShoppingCartItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ShoppingCartId");
                        });

                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Sales_API.Models.OrderAgg.Order", b =>
                {
                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("Sales_API.Models.PaymentTransactionAgg.PaymentTransaction", b =>
                {
                    b.Navigation("PaymentTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
