// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sales.Infrastructure.Persistence;

#nullable disable

namespace Sales.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    partial class SalesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sales.Domain.BillAgg.Models.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BillDiscountId")
                        .HasColumnType("uuid");

                    b.Property<int>("BillStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpirationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentSessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BillDiscountId");

                    b.ToTable("Bills", (string)null);
                });

            modelBuilder.Entity("Sales.Domain.BillAgg.Models.BillItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DiscountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("numeric");

                    b.Property<long>("ProductItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("DiscountId");

                    b.ToTable("BillItems", (string)null);
                });

            modelBuilder.Entity("Sales.Domain.DiscountAgg.Models.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("integer");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ProductItemId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Discounts", (string)null);
                });

            modelBuilder.Entity("Sales.Domain.OrderAgg.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BillId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("boolean");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Sales.Domain.PaymentSessionAgg.Models.PaymentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentGatewayUrl")
                        .HasColumnType("text");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<string>("SessionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TransactionStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PaymentTransactions", (string)null);
                });

            modelBuilder.Entity("Sales.Domain.PriceLabelAgg.Models.PriceLabel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ProductItemId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ProductItemPrices", (string)null);
                });

            modelBuilder.Entity("Sales.Domain.ShoppingCartAgg.Models.ShoppingCart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCarts", (string)null);
                });

            modelBuilder.Entity("ShoppingCartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long?>("ProductItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ShoppingCartId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("ShoppingCartItems", (string)null);
                });

            modelBuilder.Entity("Sales.Domain.BillAgg.Models.Bill", b =>
                {
                    b.HasOne("Sales.Domain.DiscountAgg.Models.Discount", "BillDiscount")
                        .WithMany()
                        .HasForeignKey("BillDiscountId");

                    b.OwnsOne("Sales.Domain.Common.ValueObjects.Money", "ShippingCost", b1 =>
                        {
                            b1.Property<Guid>("BillId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("ShippingCost_Amount");

                            b1.Property<string>("Currency")
                                .HasColumnType("text")
                                .HasColumnName("ShippingCost_Currency");

                            b1.HasKey("BillId");

                            b1.ToTable("Bills");

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.OwnsOne("Sales.Domain.Common.ValueObjects.Money", "TotalBillItemsDiscount", b1 =>
                        {
                            b1.Property<Guid>("BillId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("TotalBillItemsDiscount_Amount");

                            b1.Property<string>("Currency")
                                .HasColumnType("text")
                                .HasColumnName("TotalBillItemsDiscount_Currency");

                            b1.HasKey("BillId");

                            b1.ToTable("Bills");

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.OwnsOne("Sales.Domain.Common.ValueObjects.Money", "TotalBilling", b1 =>
                        {
                            b1.Property<Guid>("BillId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("TotalBilling_Amount");

                            b1.Property<string>("Currency")
                                .HasColumnType("text")
                                .HasColumnName("TotalBilling_Currency");

                            b1.HasKey("BillId");

                            b1.ToTable("Bills");

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.OwnsOne("Sales.Domain.Common.ValueObjects.Money", "TotalBillingDiscountedAmount", b1 =>
                        {
                            b1.Property<Guid>("BillId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("TotalBillingDiscountedAmount_Amount");

                            b1.Property<string>("Currency")
                                .HasColumnType("text")
                                .HasColumnName("TotalBillingDiscountedAmount_Currency");

                            b1.HasKey("BillId");

                            b1.ToTable("Bills");

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.OwnsOne("Sales.Domain.Common.ValueObjects.Money", "TotalItemPricesBase", b1 =>
                        {
                            b1.Property<Guid>("BillId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("TotalItemPricesBase_Amount");

                            b1.Property<string>("Currency")
                                .HasColumnType("text")
                                .HasColumnName("TotalItemPricesBase_Currency");

                            b1.HasKey("BillId");

                            b1.ToTable("Bills");

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.OwnsOne("Sales.Domain.Common.ValueObjects.Money", "TotalItemsDiscountedAmount", b1 =>
                        {
                            b1.Property<Guid>("BillId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("TotalItemsDiscountedAmount_Amount");

                            b1.Property<string>("Currency")
                                .HasColumnType("text")
                                .HasColumnName("TotalItemsDiscountedAmount_Currency");

                            b1.HasKey("BillId");

                            b1.ToTable("Bills");

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.OwnsOne("Sales.Domain.Common.ValueObjects.Money", "TotalItemsPriceWithDiscount", b1 =>
                        {
                            b1.Property<Guid>("BillId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("TotalItemsPriceWithDiscount_Amount");

                            b1.Property<string>("Currency")
                                .HasColumnType("text")
                                .HasColumnName("TotalItemsPriceWithDiscount_Currency");

                            b1.HasKey("BillId");

                            b1.ToTable("Bills");

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.OwnsOne("Sales.Domain.Common.ValueObjects.Money", "TotalTax", b1 =>
                        {
                            b1.Property<Guid>("BillId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("TotalTax_Amount");

                            b1.Property<string>("Currency")
                                .HasColumnType("text")
                                .HasColumnName("TotalTax_Currency");

                            b1.HasKey("BillId");

                            b1.ToTable("Bills");

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.OwnsOne("Sales.Domain.Common.ValueObjects.ShippingInformation", "ShippingInformation", b1 =>
                        {
                            b1.Property<Guid>("BillId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .HasColumnType("text");

                            b1.Property<string>("ContactPhoneNumber")
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text");

                            b1.Property<string>("Province")
                                .HasColumnType("text");

                            b1.Property<string>("ReceiverFirstName")
                                .HasColumnType("text");

                            b1.Property<string>("ReceiverLastName")
                                .HasColumnType("text");

                            b1.Property<int>("ShippingType")
                                .HasColumnType("integer");

                            b1.HasKey("BillId");

                            b1.ToTable("Bills");

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.Navigation("BillDiscount");

                    b.Navigation("ShippingCost")
                        .IsRequired();

                    b.Navigation("ShippingInformation")
                        .IsRequired();

                    b.Navigation("TotalBillItemsDiscount")
                        .IsRequired();

                    b.Navigation("TotalBilling")
                        .IsRequired();

                    b.Navigation("TotalBillingDiscountedAmount")
                        .IsRequired();

                    b.Navigation("TotalItemPricesBase")
                        .IsRequired();

                    b.Navigation("TotalItemsDiscountedAmount")
                        .IsRequired();

                    b.Navigation("TotalItemsPriceWithDiscount")
                        .IsRequired();

                    b.Navigation("TotalTax")
                        .IsRequired();
                });

            modelBuilder.Entity("Sales.Domain.BillAgg.Models.BillItem", b =>
                {
                    b.HasOne("Sales.Domain.BillAgg.Models.Bill", "Bill")
                        .WithMany("BillItems")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sales.Domain.DiscountAgg.Models.Discount", "Discount")
                        .WithMany()
                        .HasForeignKey("DiscountId");

                    b.OwnsOne("Sales.Domain.Common.ValueObjects.Money", "DiscountedAmount", b1 =>
                        {
                            b1.Property<Guid>("BillItemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("DiscountedAmount_Amount");

                            b1.Property<string>("Currency")
                                .HasColumnType("text")
                                .HasColumnName("DiscountedAmount_Currency");

                            b1.HasKey("BillItemId");

                            b1.ToTable("BillItems");

                            b1.WithOwner()
                                .HasForeignKey("BillItemId");
                        });

                    b.OwnsOne("Sales.Domain.Common.ValueObjects.Money", "UnitPriceBase", b1 =>
                        {
                            b1.Property<Guid>("BillItemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("UnitPriceBase_Amount");

                            b1.Property<string>("Currency")
                                .HasColumnType("text")
                                .HasColumnName("UnitPriceBase_Currency");

                            b1.HasKey("BillItemId");

                            b1.ToTable("BillItems");

                            b1.WithOwner()
                                .HasForeignKey("BillItemId");
                        });

                    b.OwnsOne("Sales.Domain.Common.ValueObjects.Money", "UnitPriceWithDiscount", b1 =>
                        {
                            b1.Property<Guid>("BillItemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("UnitPriceWithDiscount_Amount");

                            b1.Property<string>("Currency")
                                .HasColumnType("text")
                                .HasColumnName("UnitPriceWithDiscount_Currency");

                            b1.HasKey("BillItemId");

                            b1.ToTable("BillItems");

                            b1.WithOwner()
                                .HasForeignKey("BillItemId");
                        });

                    b.Navigation("Bill");

                    b.Navigation("Discount");

                    b.Navigation("DiscountedAmount")
                        .IsRequired();

                    b.Navigation("UnitPriceBase")
                        .IsRequired();

                    b.Navigation("UnitPriceWithDiscount")
                        .IsRequired();
                });

            modelBuilder.Entity("Sales.Domain.OrderAgg.Models.Order", b =>
                {
                    b.HasOne("Sales.Domain.BillAgg.Models.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("BillId");

                    b.OwnsOne("Sales.Domain.Common.ValueObjects.Money", "OrderTotal", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("OrderTotal_Amount");

                            b1.Property<string>("Currency")
                                .HasColumnType("text")
                                .HasColumnName("OrderTotal_Currency");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsMany("Sales.Domain.OrderAgg.Models.OrderItem", "OrderItems", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<long?>("ProductItemId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer");

                            b1.HasKey("OrderId", "Id");

                            b1.ToTable("OrderItems", (string)null);

                            b1.WithOwner("Order")
                                .HasForeignKey("OrderId");

                            b1.Navigation("Order");
                        });

                    b.Navigation("Bill");

                    b.Navigation("OrderItems");

                    b.Navigation("OrderTotal");
                });

            modelBuilder.Entity("Sales.Domain.PaymentSessionAgg.Models.PaymentSession", b =>
                {
                    b.OwnsOne("Sales.Domain.Common.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentSessionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("Amount_Amount");

                            b1.Property<string>("Currency")
                                .HasColumnType("text")
                                .HasColumnName("Amount_Currency");

                            b1.HasKey("PaymentSessionId");

                            b1.ToTable("PaymentTransactions");

                            b1.WithOwner()
                                .HasForeignKey("PaymentSessionId");
                        });

                    b.OwnsOne("Sales.Domain.Common.ValueObjects.Money", "BaseAmount", b1 =>
                        {
                            b1.Property<Guid>("PaymentSessionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("BaseAmount_Amount");

                            b1.Property<string>("Currency")
                                .HasColumnType("text")
                                .HasColumnName("BaseAmount_Currency");

                            b1.HasKey("PaymentSessionId");

                            b1.ToTable("PaymentTransactions");

                            b1.WithOwner()
                                .HasForeignKey("PaymentSessionId");
                        });

                    b.Navigation("Amount");

                    b.Navigation("BaseAmount");
                });

            modelBuilder.Entity("Sales.Domain.PriceLabelAgg.Models.PriceLabel", b =>
                {
                    b.OwnsOne("Sales.Domain.Common.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<long>("PriceLabelId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("Price_Amount");

                            b1.Property<string>("Currency")
                                .HasColumnType("text")
                                .HasColumnName("Price_Currency");

                            b1.HasKey("PriceLabelId");

                            b1.ToTable("ProductItemPrices");

                            b1.WithOwner()
                                .HasForeignKey("PriceLabelId");
                        });

                    b.Navigation("Price");
                });

            modelBuilder.Entity("ShoppingCartItem", b =>
                {
                    b.HasOne("Sales.Domain.ShoppingCartAgg.Models.ShoppingCart", "ShoppingCart")
                        .WithMany("ShoppingCartItems")
                        .HasForeignKey("ShoppingCartId");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("Sales.Domain.BillAgg.Models.Bill", b =>
                {
                    b.Navigation("BillItems");
                });

            modelBuilder.Entity("Sales.Domain.ShoppingCartAgg.Models.ShoppingCart", b =>
                {
                    b.Navigation("ShoppingCartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
