using Catalog_API.Exceptions;

namespace Catalog_API.Models
{
    public class Product
    {


        //Auto generated by db
        public long Id { get; private set; }
        public string Name { get; private set; }
        public string Description { get; private set; }

        public bool IsDraftMode
        {
            get
            {
                return ProductCategoryId <= 0;
            }
        }
        public long? ProductCategoryId { get; private set; }

        //Navigation property
        public ProductCategory ProductCategory { get; set; }


        private Product()
        {

        }
        public Product(string name, string desc)
        {
            SetName(name);
            SetDescription(desc);
        }

        public void Edit(string name, string desc)
        {
            SetName(name);
            SetDescription(desc);
        }

        public void SetName(string name = "")
        {
            if (name.Length < 2)
            {
                throw new ProductNameTooShortException();
            }
            Name = name;
        }

        public void SetDescription(string desc = "")
        {
            if (desc.Length < 10)
            {
                throw new ProductDescriptionTooShortException();
            }
            Description = desc;
        }

        public void AssignToProductCategory(long id)
        {
            ProductCategoryId = id;
        }
    }
}
